services:
  # =========================
  # Backend (Node + Prisma)
  # =========================
  - type: web
    name: svkp-backend
    env: node
    rootDir: backend
    plan: free
    buildCommand: |
      npm ci
      npx prisma generate
      npx prisma migrate deploy
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TRUST_PROXY
        value: "1"
      - key: PORT
        value: "5000"
      - key: DATABASE_URL
        fromDatabase:
          name: svkp-postgres
          property: connectionString
      # Si no quieres fijarlos, puedes pedir a Render que los genere:
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_SECRET
        generateValue: true
      # CORS: incluir PROD + LOCAL
      - key: FRONTEND_URL
        value: https://ventasvk.onrender.com,http://localhost:5173
      - key: USER_UPLOADS_DIR
        value: ./uploads
      - key: TIENDA_UPLOADS_DIR
        value: ./TiendaUploads

  # =========================
  # Frontend (Static Site)
  # =========================
  - type: static_site            # 👈 importante: static_site (no web)
    name: svkp-frontend
    rootDir: frontend
    plan: free
    buildCommand: npm ci && npm run build
    staticPublishPath: dist      # publica /frontend/dist
    routes:
      # Fallback SPA: cualquier ruta -> index.html
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://svkp-backend.onrender.com
      - key: VITE_FILES_BASE
        value: https://svkp-backend.onrender.com

databases:
  - name: svkp-postgres
